hello/urls.py
from django.conf.urls.defaults import *
import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    #('^$',hello_world),
    ('^$',include('weather.urls')),
    ('^weather/',include('weather.urls')),
    (r'(?P<path>^favicon\.ico$)', 'django.views.static.serve',{'document_root': settings.STATIC_ROOT}), #icon url
    (r'^blog/',include('blog.urls')),
    
    # Example:
    # (r'^hello/', include('hello.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
)


if settings.DEBUG == True:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': settings.MEDIA_ROOT}),
         (r'^(?P<path>favicon.ico$)', 'django.views.static.serve',         
         {'document_root': settings.STATIC_ROOT}),
                            
##        (r'^static/(?P<path>.*)$', 'django.views.static.serve',
##         {'document_root': settings.STATIC_ROOT}),
                            
    )

hello/weather/urls.py
from django.conf.urls.defaults import *
from hello.weather.views import *
from weather.cron import *
from weather.alarm_cron import *

urlpatterns = patterns('',
    (r'^$',index),
    (r'^update/$',update),
    (r'^dict/$',dict_iter),
    (r'announce/$',announce),
    (r'^verify/get_code/$',get_code),
    (r'verify/get_user_info/$',get_user_info),
    (r'^verify/(?P<action>\w+)/$',verify),    
    (r'^(?P<cid>\d{9}).js$', cid_js),
    (r'^cronweb/$',cronweb),
    (r'^alarmweb/$',alarmweb),
    (r'^shutdown/$',shutdown),

)

hello/weather/models.py
#! /usr/bin/env python
# coding:utf-8
import datetime, urllib2,re
from django.db import models, connection
#from django.contrib import admin
from PyWapFetion import Fetion,Errors
from BeautifulSoup import BeautifulSoup

# Create your models here.
class City(models.Model):
    cid = models.CharField(max_length =9,primary_key = True)
    province = models.CharField(max_length = 10)
    city = models.CharField(max_length = 10)
    
    @staticmethod
    def get_all_areas():
        '''
                取全部地区编码对,其中直辖市/特别行政区为9位,省份(含台湾)为5位，                
                '''                
        areas = [('101010100',u'北京'),('101020100',u'上海'),('101030100',u'天津'),('101040100',u'重庆'),('101320101',u'香港'),('101330101',u'澳门'),]
        cursor = connection.cursor()            
        sql = 'SELECT DISTINCT SUBSTR( cid, 1, 5 ) AS pid, province FROM weather_city WHERE cid>%s AND cid <>%s AND cid<>%s'            
        cursor.execute(sql,['101040100','101320101','101330101'])
        areas.extend(cursor.fetchall())                        
        return areas
    
    @staticmethod
    def get_below_cities(area_code):
        '''取指定省级下的全部城市'''
        cursor = connection.cursor()            
        sql = 'SELECT cid,city FROM weather_city WHERE cid LIKE %s'            
        cursor.execute(sql,['%s%s'% (area_code,'%')])
        return cursor.fetchall()
    
    def __unicode__(self):
        return u'%s:%s:%s' % (self.province,self.city,self.cid)
    
    class Meta:
        ordering = ['cid',]


class Weather(models.Model):
    HOURS_CHOICES = (
       ('0', '0点'),('1', '1点'),('2', '2点'),('3', '3点'),('4', '4点'),('5', '5点'),                     
       ('6', '6点'),('7', '7点'),('8', '8点'),('9', '9点'),('10', '10点'),('11', '11点'),
       ('12', '12点'),('13', '13点'),('14', '14点'),('15', '15点'),('16', '16点'),('17', '17点'),
       ('18', '18点'),('19', '19点'),('20', '20点'),('21', '21点'),('22', '22点'),('23', '23点'),
    )
    cid = models.ForeignKey(City)
    hour = models.CharField(max_length=2,choices=HOURS_CHOICES)
    info = models.TextField(blank=True)
    fetch_ts = models.DateTimeField(auto_now=True,verbose_name=u'获取时间')
    

    def __unicode__(self):
            return u"%s (每日%s时)" % (self.cid,self.hour)
        
    class Meta:
        ordering = ['-fetch_ts']
    

class UserManager(models.Manager):

    def filted_with_cid(self,cid):
        cursor = connection.cursor()
        sql = 'SELECT b.* FROM weather_city a, weather_user b, weather_weather c WHERE a.cid like %s AND a.cid=c.cid_id AND b.wid_id=c.id  AND b.active=1 ORDER BY b.id DESC'                
        cursor.execute(sql,['%s%s' % (cid,'%')])
        return [User.objects.get(id=row[0]) for row in cursor.fetchall()]
        
    
    
class User(models.Model):
    TYPE_CHOICES = (('E','每日发送三天预报'),('B','可能下雨时才发送')) 
    fid = models.CharField(verbose_name=u'飞信号',max_length = 10,blank = True,) #飞信id号，允许为空
    phone_num = models.CharField(max_length = 11)
    wid = models.ForeignKey(Weather,verbose_name=u'订阅城市/发送时间')
    sub_type = models.CharField(verbose_name=u'订阅类型',max_length=1,default='E',choices=TYPE_CHOICES) #订阅类型分别为每天一条短信和只有坏天气时发送短信
    reg_ts = models.DateTimeField(verbose_name=u'注册时间',default=datetime.datetime.now)
    active = models.BooleanField(default=True,verbose_name="是否激活")
    send_time = models.DateTimeField(default=datetime.datetime(1970,1,1,0,0,0),verbose_name=u'上次发送时间')
    objects = UserManager()
    
    def __unicode__(self):
        return self.phone_num
    
    @property
    def hour(self):
        return self.wid.hour
        
    class Meta:
        ordering = ['-reg_ts',]


#简单日志记录
class Log(models.Model):
    LEVELS = (('0','ALERT'),('1','DEBUG'),('2','INFO'))
    time = models.DateTimeField(auto_now=True,verbose_name=u'时间')
    level = models.CharField(verbose_name='等级',max_length=1,default='2',choices=LEVELS)
    event = models.TextField(verbose_name=u'事件')
    
    def __unicode__(self):
        return "%s(%s):%s" % (self.time,self.level_name(),self.event) 

    def level_name(self):
        for item in Log.LEVELS:
            if item[0] == self.level:
                return item[1]  


#天气预警
class Alarm(models.Model):
    color_id = models.CharField(verbose_name=u'预警颜色编号',max_length=8)
    title = models.TextField(verbose_name=u'预警标题')
    url = models.CharField(verbose_name=u'预警内容页网址',max_length=100)
    area_code = models.CharField(verbose_name=u'地区代号',max_length=9,default='0')    
    content = models.TextField(verbose_name=u'预警内容',blank=True)    
    pub_time = models.DateTimeField(verbose_name=u'发布时间')
    fetch_time = models.DateTimeField(verbose_name=u'获取时间',auto_now=True)

    class Meta:
        ordering = ['-id']    
    
    def __unicode__(self):
        return "%s(%s-%s)" % (self.title,self.area_code,self.pub_time)     
    
    '''在线取得预警信息,参数表示是否过滤含解除字样的预警信息，默认过滤'''
    @staticmethod
    def fetch_online(cancel=True):
        alarm_url = 'http://www.nmc.gov.cn/alarm/index.htm'
        page = urllib2.urlopen(alarm_url).read()
        soup = BeautifulSoup(page)
        tds = soup.findAll('td', width="28")
        alarms = []
        now = datetime.datetime.now()
        for td in tds :
            title_td = td.nextSibling.nextSibling
            title = title_td.contents[1].text.strip()
            pub_time = title_td.nextSibling.nextSibling.text.replace('&nbsp;','')
            pub_time = Alarm.chdate_convert(pub_time)
            if pub_time > now : continue #为了处理气象网站发布日期错误的情况
            if cancel and u'解除' in title: continue                
            info = {
                'color_id':td.contents[1]['id'],            
                'url':title_td.contents[1]['href'],
                'title':title,
                'pub_time': pub_time
            }
             
            alarms.append(info)
        return alarms
        
    @staticmethod
    def chdate_convert(chdate):        
        pattern = re.compile(ur'(?P<year>\d+)年(?P<month>\d+)月(?P<day>\d+)日(?P<hour>\d+)时',re.U)
        match = pattern.match(chdate)
        if match:
            # 使用Match获得分组信息
            datetime_tuple = (int(num) for num in list(match.groups()))    
            return datetime.datetime(*datetime_tuple)
        else :
            raise ValueError('chinese date formate convert error')
            
    @staticmethod
    def fetch_content(url=''):        
        if '' == url : url = '/sjyj/0002004/201206271832594311.htm'
        url = 'http://www.nmc.gov.cn%s' % url
        page = urllib2.urlopen(url).read()
        soup = BeautifulSoup(page)
        alarmtexts = soup.findAll(id=re.compile('alarmtext'))
        if u'解除' in alarmtexts[0].text:
            return alarmtexts[0].text.strip()
        return '\n'.join([alarmtext.text.strip() for alarmtext in alarmtexts])

        

#预警发送日志
class AlarmLog(models.Model):
    alarm = models.ForeignKey(Alarm)
    user = models.ForeignKey(User)
    details = models.TextField(verbose_name=u'详细信息',blank=True)
    send_time = models.DateTimeField(verbose_name=u'发送时间',auto_now=True)
    
    def __unicode__(self):
        return u'%s/%s' % (self.user,self.alarm)
        
    class Meta:
        ordering = ['-send_time']            
        
class MyFetion(Fetion):
    test_id = '299396032'
    limit =5
    
    def __init__(self,mobile,password,status='4',cachefile=None,keepalive=False):
        super(MyFetion,self).__init__(mobile,password,status,cachefile,keepalive)
    
    #定义最大尝试次数
    #默认不是非得发到对方手机
    def sendBYid(self,id,message,sm=False):
         
        for i in range(self.limit):
                try:                    
                    if super(MyFetion,self).sendBYid(id,message,sm=sm) == True:
                        break
                    else :
                        i+=1
                except Errors.FetionNotYourFriend, e:
                    i+=1
                    #如果在一天内不确认好友关系，则删除用户的注册关系
                    #这样会导致过期后用户确认加好友，也会无效。需要重新注册
                    try:
                        not_friend = User.objects.get(fid=id)
                    except User.DoesNotExist:
                        pass
                    else:  
                        delta = datetime.datetime.now() - not_friend.reg_ts                                              
                        if  delta.days > 0:                            
                            not_friend.active = False
                            not_friend.save()
                            res = "Success" if not_friend.delete() == None else "Failed" 
                            Log(level=1,event='%s to delete not friend :%s ' % (res ,not_friend.phone_num)).save()
                                                
                    Log(level=1,event='fid:%s is not your Friend' % id).save()
                    return None
                except Exception, e:
                    i+=1
                    #err_info = sys.exc_info()
                    #event = '%s : %s ' % (err_info[0],err_info[1])
                    #pritn event
                    #Log(event=event).save()
                    self._login()
                    
                    
                finally:
                    pass
                
        else:
                Log(event = u"send sms trying too many times,,Fid: %s " % id).save() 
                return False
        return True

hello/weather/forms.py
#coding:utf-8
from django import forms
from settings import FETION
from weather.models import Weather, User, City, MyFetion, Log
from weather.PyWapFetion import Fetion
from  django.core.exceptions import ValidationError
import re


CHOICES = (('0', '--请选择--'),)

class ProvinceChoiceField(forms.ChoiceField):
    def validate(self, value):
        if value == '0':
            raise ValidationError(u'请选择正确的省份')
        
class CityChoiceField(forms.ChoiceField):    

    def validate(self, value):
        if not re.match(r'^\d{9}$', value):
            raise ValidationError(u'请选择正确的城市')

        if not City.objects.filter(cid=value):
            raise ValidationError('无效城市代号')
       

class SubscribeForm(forms.Form):
    
    province = ProvinceChoiceField(choices=CHOICES, label="省份",
                                 widget=forms.Select(attrs={'id':'province', 'class':'province', 'onchange':'on_pro_select_change(this.id)'}),
                                 )
    
    city = CityChoiceField(choices=CHOICES, label="城市",
                             widget=forms.Select(attrs={'id':'city', 'class':'city', 'onchange':'on_city_change(this.id)'}),
                             
                             )
     
    hour = forms.ChoiceField(choices=Weather.HOURS_CHOICES, label='发送时间',
                                 widget=forms.Select(attrs={'id':'hour', 'class':'hour'})
                                 )
    sub_type = forms.ChoiceField(widget=forms.RadioSelect(attrs={'class':'subtype', 'id':'subtype'}), initial={'sub_type':'E'}, choices=User.TYPE_CHOICES, label='订阅类型')
    
    phone_num = forms.CharField(label='手机号码', min_length=11, max_length=11, widget=forms.TextInput(attrs={'id':'phone_num'}))
    
    def clean_phone_num(self):
        
        phone_num = self.cleaned_data['phone_num']
        Log(level=2,event='%s tried to subscribe' % phone_num).save()        
        #self.phone_num = phone_num
        china_mobile_num = ('134','135','136','137','138','139','150','151','152','158','159','157','187','188','147')
        if phone_num[0:3] not in china_mobile_num:
            raise ValidationError('非中国移动号码不能注册')
        try:            
            user = User.objects.get(phone_num=phone_num)
        except User.DoesNotExist:
            pass
        else :
            if user.active == True :
                raise ValidationError('你已经注册过了')
            else :
                raise ValidationError('帐户已冻结,请激活后继续使用')
        
        #这里的管理员手机可能使用模型存取
        phone = FETION[0][0]
        psw = FETION[0][1]
        ft = MyFetion(phone, psw)
        fid = ft.findid(phone_num)
        ft.logout()
        if fid == None:
            raise ValidationError('无效手机号或没有开通飞信服务')
        else :
            
            self.fid = fid
            return phone_num
        


# 验证表
class VerifyForm(forms.Form):
       
    phone_num = forms.CharField(label='手机号码', min_length=11, max_length=11, widget=forms.TextInput(attrs={'id':'phone_num'}))
    code = forms.CharField(label='验证码', min_length=6, max_length=6, widget=forms.TextInput(attrs={'id':'code'}))     
    #phone_num =  SubscribeForm.phone_num
    #def clean_phone_num(self):
        



class CodeForm(forms.Form):
       
    phone_num = forms.CharField(label='手机号码', min_length=11, max_length=11, widget=forms.TextInput(attrs={'id':'phone_num'}))

    def clean_phone_num(self):
            
        phone_num = self.cleaned_data['phone_num']
        Log(level=2,event='%s required for verify code' % phone_num).save()        
        #self.phone_num = phone_num
        try:            
            user = User.objects.get(phone_num=phone_num)
            self.fid = user.fid
        except User.DoesNotExist:
            raise ValidationError('找不到该帐户，请先注册。')
                                    
        return phone_num    

class UpdateSubForm(forms.Form):
    province = ProvinceChoiceField(choices=CHOICES, label="省份",
                                 widget=forms.Select(attrs={'id':'province', 'class':'province', 'onchange':'on_pro_select_change(this.id)'}),
                                 )
    
    city = CityChoiceField(choices=CHOICES, label="城市",
                             widget=forms.Select(attrs={'id':'city', 'class':'city', 'onchange':'on_city_change(this.id)'}),
                             
                             )
     
    hour = forms.ChoiceField(choices=Weather.HOURS_CHOICES, label='发送时间',
                                 widget=forms.Select(attrs={'id':'hour', 'class':'hour'})
                                 )
    sub_type = forms.ChoiceField(widget=forms.RadioSelect(attrs={'class':'subtype', 'id':'subtype'}), initial={'sub_type':'E'}, choices=User.TYPE_CHOICES, label='订阅类型')
    
    
    
    
    

hello/weather/templates/announce.html
{% extends "index.html" %}
{% block title %} {{ msg }}, 感谢使用本程序，此服务免费{% endblock %}

{% block content %}
{{ block.super }}

 <div class="content_wrap">
 
 {% ifnotequal user None %}
 <dl id="sub_info">
 <dt>你的订阅信息如下:</dt>
 <dd>手机号码:{{ user.phone_num }}</dd>
 {#<dd>飞信ID:{{user.fid}}</dd>#}
 <dd>订阅城市/发送时间 :{{user.wid.cid.city}}/{{user.wid.get_hour_display}}</dd>
 <dd>订阅类型:
 {{user.get_sub_type_display}}
 </dd>
 <dd>【<a href="javascript:window.close()"><font color="#000000">关闭窗口</font></a>】</dd>
 </dl>
 {% endifnotequal %} 
 
</div>

{% endblock %}

hello/weather/templates/base.html
<!DOCTYPE HTML>
<html lang="zh-cn">
<head>
{% block meta %}
<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
{% endblock %}
{% block js %} 
<script type="text/javascript" src="{{ STATIC_URL }}weather/jquery.js"></script>
{% endblock %}
{% block css %}

<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}weather/main.css?version=1.2" />
<style type="text/css">
dd {margin: 5px 0}
ul,li {margin:0;padding:0}
.errorlist {color:red; }
#sub_type ul {display: inline;}
#sub_type li {display:inline}
</style> 
{% endblock %}
<title>{% block title %}{% endblock %}</title>
</head>
<body>

<div id="forecast">
    <ul>
        <li class="cast" id="location"></li>
        <li class="cast" id="today_cast"></li>
        <li class="cast" id="tomorrow_cast"><li>       
        <li class="cast" id="ip_address"><li>
    </ul>
</div>


<div id="wrapper">

{% block content %}
{% endblock %}

{% block about %}
<dl id="about" class="content_wrap">
<dt>订制说明：</dt>

<dd>0. 本应用已移植至新浪云计算开发平台(SAE)，大幅提高国内访问速度, 传送门: <a href="http://sms128.sinaapp.com/" id="nothing">请猛击我</a></dd>
<dd>1. 免费为中国移动用户（需要先开通飞信) 提供天气预报短信，支持两种订制方式。实用灵活。
</dd>

<dd>2. 输入手机号码，接受加为好友的飞信通知即可，提供本站退订或者在好友列表中删除本站飞信用户。</dd>

<dd>3. 全部天气数据来自中央气象台中国天气网, 准确度高。</dd>

<dd> 4. 本站承诺绝对不会公开用户个人隐私数据，更不会向用户发送天气预报以外的信息。
</dd>
<dd>5. 这是本人学习Python, <a href="www.djangoproject.com" target="_blank" >Django</a>, git ,dotcloud的实践项目， 非商业应用，开放源码。<a target="_blank" href="https://github.com/falconchen/FetionWether">项目主页</a></dd>

<dd>6. 有建议、合作或使用问题请联系作者:<a href="www.onephper.tk">Falcon</a> | <a href="http://wpa.qq.com/msgrd?V=1&Uin=516974090&Site=tq.sms128.net/FoolCoder&Menu=yes" target="_blank">qq:516974090</a> | Email:falcon_chen#qq.com</dd>


</dl>
{% endblock %}

{% block footer %}
<div id="footer"> Coded by Falcon <a href="http://www.onephper.tk" target="_blank" > 雕刻时光</a> June,2012 
</div>
{% endblock %}


</div>
<div id="right_side">
<div id="votes">
<div class="title"><span class="leftBorder"></span><span class="midBlock">短信样式预览</span><span class="rightBorder"></span></div>
<div id="vote_content">
<dl>
           <p>天气短信1:每日发送三天预报</p>
	       <p><img src="/static/weather/weather_sms.gif" /></p>
           <p>天气短信2:可能下雨时才发送</p>
	       <p><img src="/static/weather/weather_sms.png" /></p>
     		     
           <p>预警短信</p>
	       <p><img src="/static/weather/alarm_sms.gif" /></p>
     	
</dl>
</div>
</div>
</div>

</body>
{% block tongji %}
<script type="text/javascript">
var _bdhmProtocol = (("https:" == document.location.protocol) ? " https://" : " http://");
document.write(unescape("%3Cscript src='" + _bdhmProtocol + "hm.baidu.com/h.js%3Ffa72f8e59b6fb38e797c7a086827fb24' type='text/javascript'%3E%3C/script%3E"));
</script>
<script src="http://app.baidu.com/static/appstore/monitor.st"></script>
{% endblock %}

</html>

hello/weather/templates/dict.html
<!DOCTYPE HTML>
<html lang="zh-cn">
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8" />

<title></title>
</head>
<body>

  {% for item,value in metas.iteritems reversed %}
    {% if forloop.first %}<ul> {% endif %}
      <li>{{ item.lower }} : {{ value }}</li>
    {% if forloop.last %}</ul> {% endif %}
  {% empty %}
    <p>迭代对象为空</p>
  {% endfor %}

</body>
</html>

hello/weather/templates/index.html
{% extends "base.html" %}
{% comment %}
{% load static %}
{% get_static_prefix as STATIC_PREFIX %}
{% endcomment %}
{% block meta %}
{{ block.super }}
<meta  name="keywords" content="免费短信, 天气预报, 飞信天气,">
<meta  name="description" content="飞信免费天气预报短信订制服务。">
{% endblock %}


{% block js %}
{{ block.super }}
<script type="text/javascript" src="{{ STATIC_URL }}weather/jdata.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}weather/main2.js?version=1.2"></script>
{% endblock %}
{% block title %} 免费订制短信天气预报首页 {% endblock %}

{% block content %}
<h1><a href="/" title="用手机订阅你的天气">飞信天气网</a></h1>
<h2 style='float:left'>飞信免费天气预报短信订制服务。</h2>
<br/>
<div id="left_side">
{% block nav %}
<div id="nav">
    <span class="leftBorder"></span>
    <a  id="insert" href="/">我要订制</a>
	<a id="update" href="/weather/verify/update/">更改订阅</a>
	<a id="deactive" href="/weather/verify/deactive/">退订</a>
	<a id="active" href="/weather/verify/active/">重新激活</a>	
<a href="http://sms128.sinaapp.com" target="_blank">国内访问地址(Beta)</a>
    <span class="rightBorder"></span>
</div>
{% endblock %}
<div class="subTitle">
{% ifnotequal msg None %}
<div id='msg'>{{ msg|escape }}</div>
{% endifnotequal %}
</div>



{% ifnotequal form None %}
<div class="content_wrap">
<h3><b>公告:</b> 气象灾害预警短信正在测试, 已移植到SAE, 改善国内访问速度.<a href="http://sms128.sinaapp.com/" id="nothing">体验地址</a></h3>

	<form action="" method="post" id="{{ form_id }}">
	{% if form.errors %}
	    <p style="color: red;font-weight: bold">
	        {# Please correct the error{{ form.errors|pluralize }} below. #}
	         出错了，请检查相关字段
	    </p>
	{% endif %}	
		
		
	<dl>
		{% if not form.phone_num %} <dt>设置你的订阅信息</dt>{% endif %}
	{% comment %}	
		{{ form.as_ul }}
	{% endcomment %}
		{% block fields %}
		<dd>
			{{ form.province.errors }}
			{{ form.city.errors }}
			<label for='province'>省份地区:</label>
			{{ form.province }}	
			<label for='city'>城市:</label>
			{{ form.city }}
		</dd>
		{% if form.phone_num %}
		<dd>
			
			<label for='phone_num'>手机号码:</label>
			{{ form.phone_num }}<strong style="color:red">*</strong>
           {{ form.phone_num.errors }} 
		</dd>
		{% endif %}
		<dd>
			{{ form.hour.errors }}
			<label for='hour'>发送时间:</label>
			{{ form.hour }}
		</dd>
		
		<dd id="sub_type">
			{{ form.sub_type.errors }}
			<label for='sub_type'>订阅类型:</label>
			{{ form.sub_type }}
			
		</dd>	
		{% endblock %}
		 
	</dl>
	{% csrf_token %}
	<input class="submit" type="submit" value="确定">
{% if action %}
	<input type="hidden" name="action"  value="{{ action }}">
{% endif %}
	</form>	

</div>
{% endifnotequal %}

{% endblock %}
</div>

hello/weather/templates/shutdown.html
{% extends "index.html" %}
{% block title %} {{ msg }}, 感谢使用本程序，此服务免费{% endblock %}

{% block content %}
{{ block.super }}

 <div class="content_wrap">
 
{{details}}
 
</div>

{% endblock %}

hello/weather/templates/sms.html
你的验证码为“{{ code }}” --飞信天气网:http://tq.sms128.net

hello/weather/templates/user_info.html
您当前的订阅信息:
{% comment %}
手机:{{msg.phone_num}}
飞信id:{{msg.fid}}
{% endcomment %}
订阅地区:{{msg.area}}
订阅类型:{{msg.sub_type}}

hello/weather/templates/verify.html
{% extends "index.html" %}
{% block title%}手机号码验证-{{ title }}{% endblock %}
{% block fields %}
		<dd>
			{{ form.phone_num.errors }}
			<label for='phone_num'>手机号:</label>
			{{ form.phone_num }}
			<a id="get_code" href='../get_code/'>点此获取验证码</a>
		</dd>
		<dd>
			{{ form.code.errors }}
			<label for='code'>验证码:</label>
			{{ form.code }}
		</dd>
		<input type="hidden" name="action" value='{{ action }}' title="{{ title }}">
{% endblock %}